database:
  uri: "mongodb://admin:admin123@10.100.3.13:27017/"
  database: "gmr-mro-staging-5y"

excel_files:
  data_path: "D:/Projects/gmr-mro/estima-ai/Data"


aircraft_details_columns:
  - "Customer Order #"
  - "Customer Name"
  - "Package #"
  - "Aircraft Reg #"
  - "A/C AGE"
  - "Aircraft Model"
  - "A/C AGE 2024"
  - "Release Tracking #"
  - "Issue Date"
  - "Package Details"
  - "CHECK CATEGORY"
  - "Type of Check"
  - "FH"
  - "FC"
  - "Start date"
  - "End date"
  - "TAT"


task_parts_columns:
  - "RTModeFlag"
  - "DeleteFlag"
  - "Task #"
  - "Requested Part #"
  - "Issued Part #"
  - "Issued Serial #"
  - "Issued Lot #"
  - "Issued Quantity"
  - "Used Quantity"
  - "UOM"
  - "Pending Return Qty"
  - "Returned Qty - Excess"
  - "Part Description"
  - "Requested Stock Status"
  - "Material Request #"
  - "Part Type"
  - "Issued Stock Status"
  - "Issue #"
  - "Material Cost"
  - "Requested Qty"



sub_task_parts_columns:
  - "Sl.No"
  - "Regn#"
  - "Package #"
  - "Task #"
  - "Task Description"
  - "Issued Part #"
  - "Part Description"
  - "Issued UOM"
  - "Stock Status"
  - "Used Qty"
  - "Base Currency"
  - "Base Price (USD)"
  - "Freight"
  - "Admin Charges"
  - "Total Billable Price"
  - "Billable Value (USD)"
  - "SOI_TRAN  #"

task_description_columns:
  - "RTModeFlag"
  - "DeleteFlag"
  - "Seq #"
  - "Task #"
  - "ATA #"
  - "Description"
  - "Add New Execution Comments"
  - "Previous Execution Comments"
  - "Status"
  - "Source Task/Discrep. #"
  - "Source Tracking #"
  - "Work Center #"
  - "Sign Off Status"
  - "Task Type"
  - "Task Category"
  - "Job Type"
  - "Repair Class."
  - "Exe. Phase"
  - "Exec. Category"
  - "Part #"
  - "Serial #"
  - "Position Code"
  - "Part Description"
  - "Repair Agency"
  - "Mech Req?"
  - "Mech Sign Off"
  - "Insp Req?"
  - "Insp Sign Off"
  - "RII Req?"
  - "RII Sign Off"
  - "Addl. Sign Off"
  - "Add New Sign Off Comments"
  - "Previous Sign Off Comments"
  - "Planned Start Date"
  - "Planned End Date"
  - "Est. Man Hrs."
  - "Actual Start Date"
  - "Actual End Date"
  - "Actual Man Hrs."
  - "Tracking #"
  - "Maint. Manual Ref. #"
  - "Long Description"
  - "Hold Status"
  - "Estimation Status"
  - "File Name"
  - "Skill #"
  - "Zone #"
  - "Work Area #"
  - "WBS Code"
  - "Parent Task #"
  - "Root Task #"
  - "Workscoping Comments"
  - "Message Center"

sub_task_description_columns:
  - "RTModeFlag"
  - "DeleteFlag"
  - "Type"
  - "Log Item #"
  - "ATA #"
  - "Description"
  - "Corrective Action"
  - "Discrepancy #"
  - "Action"
  - "Status"
  - "Source Task/Discrep. #"
  - "Source Tracking #"
  - "Work Center #"
  - "Sign Off Status"
  - "Contract Classification"
  - "Category"
  - "Exe. Phase"
  - "Exec. Category"
  - "Part Required?"
  - "Corrosion Related?"
  - "Major Item?"
  - "Repeat?"
  - "Part #"
  - "Serial #"
  - "Position Code"
  - "Part Description"
  - "Radio Communication"
  - "Reported By"
  - "Reported Date"
  - "Mech Req?"
  - "Mech Sign Off"
  - "Mech Skill #"
  - "Insp Req?"
  - "Insp Sign Off"
  - "Insp Skill #"
  - "RII Req?"
  - "RII Sign Off"
  - "RII Skill #"
  - "Addl. Sign Off"
  - "Add New Sign Off Comments"
  - "Previous Sign Off Comments"
  - "Planned Start Date"
  - "Planned End Date"
  - "Est. Man Hrs."
  - "Actual Start Date"
  - "Actual End Date"
  - "Actual Man Hrs."
  - "Seq #"
  - "Tracking #"
  - "Source Tracking #\xa0"
  - "Hold Status"
  - "Estimation Status"
  - "File Name"
  - "Skill #"
  - "Zone #"
  - "Work Area #"
  - "Deferral FH"
  - "Deferral FC"
  - "Deferral Parameter"
  - "Deferral Value"
  - "Deferral Calendar Value"
  - "Deferral Calendar"
  - "Deferral Item #"
  - "Deferral Type"
  - "Reason for Deferral"
  - "Auth. Ref. #"
  - "Message Center"

task_parts_columns_mappings:
  "RTModeFlag": "rt_mode_flag"
  "DeleteFlag": "delete_flag"
  "Task #": "task_number"
  "Requested Part #": "requested_part_number"
  "Issued Part #": "issued_part_number"
  "Issued Serial #": "issued_serial_number"
  "Issued Lot #": "issued_lot_number"
  "Issued Quantity": "issued_quantity"
  "Used Quantity": "used_quantity"
  "UOM": "unit_of_measurement"
  "Pending Return Qty": "pending_return_quantity"
  "Returned Qty - Excess": "returned_quantity_excess"
  "Part Description": "part_description"
  "Requested Stock Status": "requested_stock_status"
  "Material Request #": "material_request_number"
  "Part Type": "part_type"
  "Issued Stock Status": "issued_stock_status"
  "Issue #": "issue_number"
  "Material Cost": "material_cost"
  "Requested Qty": "requested_quantity"
  "package": "package_number"

task_description_columns_mappings:
  "RTModeFlag": "rt_mode_flag"
  "DeleteFlag": "delete_flag"
  "Seq #": "sequence_number"
  "Task #": "task_number"
  "ATA #": "ata_number"
  "Description": "description"
  "Add New Execution Comments": "add_new_execution_comments"
  "Previous Execution Comments": "previous_execution_comments"
  "Status": "status"
  "Source Task/Discrep. #": "source_task_discrepancy_number"
  "Source Tracking #": "source_tracking_number"
  "Work Center #": "work_center_number"
  "Sign Off Status": "sign_off_status"
  "Task Type": "task_type"
  "Task Category": "task_category"
  "Job Type": "job_type"
  "Repair Class.": "repair_classification"
  "Exe. Phase": "execution_phase"
  "Exec. Category": "execution_category"
  "Part #": "part_number"
  "Serial #": "serial_number"
  "Position Code": "position_code"
  "Part Description": "part_description"
  "Repair Agency": "repair_agency"
  "Mech Req?": "mechanic_required"
  "Mech Sign Off": "mechanic_sign_off"
  "Insp Req?": "inspection_required"
  "Insp Sign Off": "inspection_sign_off"
  "RII Req?": "rii_required"
  "RII Sign Off": "rii_sign_off"
  "Addl. Sign Off": "additional_sign_off"
  "Add New Sign Off Comments": "add_new_sign_off_comments"
  "Previous Sign Off Comments": "previous_sign_off_comments"
  "Planned Start Date": "planned_start_date"
  "Planned End Date": "planned_end_date"
  "Est. Man Hrs.": "estimated_man_hours"
  "Actual Start Date": "actual_start_date"
  "Actual End Date": "actual_end_date"
  "Actual Man Hrs.": "actual_man_hours"
  "Tracking #": "tracking_number"
  "Maint. Manual Ref. #": "maintenance_manual_reference_number"
  "Long Description": "long_description"
  "Hold Status": "hold_status"
  "Estimation Status": "estimation_status"
  "File Name": "file_name"
  "Skill #": "skill_number"
  "Zone #": "zone_number"
  "Work Area #": "work_area_number"
  "WBS Code": "wbs_code"
  "Parent Task #": "parent_task_number"
  "Root Task #": "root_task_number"
  "Workscoping Comments": "workscoping_comments"
  "Message Center": "message_center"
  "package": "package_number"


sub_task_description_columns_mappings:
  "RTModeFlag": "rt_mode_flag"
  "DeleteFlag": "delete_flag"
  "Type": "task_type"
  "Log Item #": "log_item_number"
  "ATA #": "ata_number"
  "Description": "task_description"
  "Corrective Action": "corrective_action"
  "Discrepancy #": "discrepancy_number"
  "Action": "action_taken"
  "Status": "task_status"
  "Source Task/Discrep. #": "source_task_discrepancy_number"
  "Source Tracking #": "source_tracking_number"
  "Work Center #": "work_center_number"
  "Sign Off Status": "sign_off_status"
  "Contract Classification": "contract_classification"
  "Category": "task_category"
  "Exe. Phase": "execution_phase"
  "Exec. Category": "execution_category"
  "Part Required?": "part_required"
  "Corrosion Related?": "corrosion_related"
  "Major Item?": "major_item"
  "Repeat?": "is_repeat"
  "Part #": "part_number"
  "Serial #": "serial_number"
  "Position Code": "position_code"
  "Part Description": "part_description"
  "Radio Communication": "radio_communication"
  "Reported By": "reported_by"
  "Reported Date": "reported_date"
  "Mech Req?": "mechanical_required"
  "Mech Sign Off": "mechanical_sign_off"
  "Mech Skill #": "mechanical_skill_number"
  "Insp Req?": "inspection_required"
  "Insp Sign Off": "inspection_sign_off"
  "Insp Skill #": "inspection_skill_number"
  "RII Req?": "rii_required"
  "RII Sign Off": "rii_sign_off"
  "RII Skill #": "rii_skill_number"
  "Addl. Sign Off": "additional_sign_off"
  "Add New Sign Off Comments": "new_sign_off_comments"
  "Previous Sign Off Comments": "previous_sign_off_comments"
  "Planned Start Date": "planned_start_date"
  "Planned End Date": "planned_end_date"
  "Est. Man Hrs.": "estimated_man_hours"
  "Actual Start Date": "actual_start_date"
  "Actual End Date": "actual_end_date"
  "Actual Man Hrs.": "actual_man_hours"
  "Seq #": "sequence_number"
  "Tracking #": "tracking_number"
  "Source Tracking #\xa0": "source_tracking_number_with_space"
  "Hold Status": "hold_status"
  "Estimation Status": "estimation_status"
  "File Name": "file_name"
  "Skill #": "skill_number"
  "Zone #": "zone_number"
  "Work Area #": "work_area_number"
  "Deferral FH": "deferral_fh"
  "Deferral FC": "deferral_fc"
  "Deferral Parameter": "deferral_parameter"
  "Deferral Value": "deferral_value"
  "Deferral Calendar Value": "deferral_calendar_value"
  "Deferral Calendar": "deferral_calendar"
  "Deferral Item #": "deferral_item_number"
  "Deferral Type": "deferral_type"
  "Reason for Deferral": "reason_for_deferral"
  "Auth. Ref. #": "authorization_reference_number"
  "Message Center": "message_center"
  "package": "package_number"

aircraft_details_column_mappings:
  "Customer Order #": "customer_order_number"
  "Customer Name": "customer_name"
  "Package #": "package_number"
  "Aircraft Reg #": "aircraft_registration_number"
  "A/C AGE": "aircraft_age"
  "Aircraft Model": "aircraft_model"
  "A/C AGE 2024": "aircraft_age_2024"
  "Release Tracking #": "release_tracking_number"
  "Issue Date": "issue_date"
  "Package Details": "package_details"
  "CHECK CATEGORY": "check_category"
  "Type of Check": "type_of_check"
  "FH": "flight_hours"
  "FC": "flight_cycles"
  "Start date": "start_date"
  "End date": "end_date"
  "TAT": "turnaround_time"
  "year": "year"





sub_task_parts_column_mappings:
  "Regn#": "registration_number"
  "Package #": "package_number"
  "Task #": "task_number"
  "Task Description": "task_description"
  "Issued Part #": "issued_part_number"
  "Part Description": "part_description"
  "Issued UOM": "issued_unit_of_measurement"
  "Stock Status": "stock_status"
  "Used Qty": "used_quantity"
  "Base Currency": "base_currency"
  "Base Price (USD)": "base_price_usd"
  "Freight": "freight_cost"
  "Admin Charges": "admin_charges"
  "Total Billable Price": "total_billable_price"
  "Billable Value (USD)": "billable_value_usd"
  "SOI_TRAN  #": "soi_transaction"
